# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelado_bd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoConcurso',
            fields=[
                ('dni', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=80)),
                ('resultado', models.CharField(choices=[('DENEGADO', 'DENEGADO'), ('OBTIENE PLAZA', 'OBTIENE PLAZA'), ('PEND. DESTINO', 'PENDIENTE DESTINO')], max_length=40)),
                ('centro_anterior', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='concurso_centro_ant', to='modelado_bd.Centro')),
                ('centro_definitivo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='concurso_centro_def', to='modelado_bd.Centro')),
            ],
            options={
                'db_table': 'resultados_concurso',
            },
        ),
    ]
