# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelado_bd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoConcurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='modelado_bd.Centro')),
            ],
        ),
    ]
