# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traslados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadoconcurso',
            old_name='centro',
            new_name='centro_anterior',
        ),
    ]
