# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelado_bd', '0001_initial'),
        ('traslados', '0002_auto_20160331_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoconcurso',
            name='centro_definitivo',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='concurso_centro_def', to='modelado_bd.Centro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultadoconcurso',
            name='centro_anterior',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='concurso_centro_ant', to='modelado_bd.Centro'),
        ),
    ]
