# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslados', '0003_auto_20160331_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoconcurso',
            name='id',
        ),
        migrations.AddField(
            model_name='resultadoconcurso',
            name='dni',
            field=models.CharField(db_index=True, default='', max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='resultadoconcurso',
            table='resultados_concurso',
        ),
    ]
