# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslados', '0004_auto_20160331_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoconcurso',
            name='nombre_completo',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadoconcurso',
            name='resultado',
            field=models.CharField(choices=[('DENEGADO', 'DENEGADO'), ('OBTIENE PLAZA', 'OBTIENE PLAZA'), ('PEND. DESTINO', 'PENDIENTE DESTINO')], default='', max_length=40),
            preserve_default=False,
        ),
    ]
