# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traslados', '0005_auto_20160406_0649'),
        ('traslados', '0005_auto_20160404_1441'),
    ]

    operations = [
    ]
