# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterinoMaestroDisponible',
            fields=[
                ('dni', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=60)),
                ('tipo_bolsa', models.CharField(max_length=10)),
                ('orden_bolsa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='interinomaestrodisponible',
            name='provincia',
            field=models.ManyToManyField(to='intcalc.Provincia'),
        ),
    ]
