# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelado_bd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.IntegerField()),
                ('minutos', models.IntegerField()),
                ('sumario', models.CharField(max_length=250)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc_destino', to='modelado_bd.Localidad')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc_origen', to='modelado_bd.Localidad')),
            ],
            options={
                'db_table': 'rutas',
            },
        ),
        migrations.AlterField(
            model_name='interinodisponible',
            name='tipo_bolsa',
            field=models.CharField(choices=[('0', 'Bolsa 0'), ('1', 'Bolsa 1'), ('2D', 'Bolsa 2D'), ('2F', 'Bolsa 2F'), ('2H', 'Bolsa 2H'), ('2J', 'Bolsa 2J'), ('2K', 'Bolsa 2K'), ('2L', 'Bolsa 2L'), ('2M', 'Bolsa 2M'), ('3H', 'Bolsa 3H'), ('3G', 'Bolsa 3G'), ('2', 'Bolsa 2'), ('3', 'Bolsa 3'), ('4F', 'Bolsa 4F'), ('4', 'Bolsa 4'), ('6M', 'Bolsa 6M'), ('6', 'Bolsa 6'), ('7G', 'Bolsa 7G'), ('7P', 'Bolsa 7P'), ('7J', 'Bolsa 7J'), ('8', 'Bolsa 8'), ('P0', 'Bolsa P0'), ('P1B', 'Bolsa P1B'), ('P1', 'Bolsa P1'), ('P2', 'Bolsa P2'), ('P4', 'Bolsa P4'), ('R1', 'Bolsa R1'), ('2N', 'Bolsa 2N'), ('4E', 'Bolsa 4E'), ('4G', 'Bolsa 4G'), ('R1H', 'Bolsa R1H'), ('R1F', 'Bolsa R1F'), ('R1D', 'Bolsa R1D'), ('R1G', 'Bolsa R1G'), ('R1I', 'Bolsa R1I')], max_length=10),
        ),
    ]
