# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelado_bd', '0002_auto_20160414_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalidadOpos2016',
            fields=[
                ('codigo_localidad', models.CharField(db_index=True, max_length=12, primary_key=True, serialize=False)),
                ('nombre_localidad', models.CharField(max_length=80)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelado_bd.Provincia')),
            ],
            options={
                'db_table': 'localidades_opos_2016',
            },
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc_origen', to='modelado_bd.LocalidadOpos2016'),
        ),
    ]
