# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelado_bd', '0002_inscripcionjornadas_enviado_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterinoDisponible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('dni', models.CharField(max_length=12)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('tipo_bolsa', models.CharField(choices=[('0', 'Bolsa 0'), ('8', 'Bolsa 8'), ('P2', 'Bolsa P2'), ('P4', 'Bolsa P4'), ('R1', 'Bolsa R1'), ('R1H', 'Bolsa R1H')], max_length=10)),
                ('orden_bolsa', models.IntegerField()),
                ('ingles', models.BooleanField()),
                ('frances', models.BooleanField()),
                ('provincia', models.ManyToManyField(to='modelado_bd.Provincia')),
            ],
        ),
        migrations.AlterModelOptions(
            name='inscripcionjornadas',
            options={'ordering': ['apellido1', 'apellido2']},
        ),
        migrations.RenameField(
            model_name='inscripcionjornadas',
            old_name='enviado_email',
            new_name='confirmada',
        ),
    ]
