# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelado_bd', '0003_auto_20160406_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='interinodisponible',
            name='especialidad',
            field=models.ManyToManyField(to='modelado_bd.Especialidad'),
        ),
        migrations.AlterField(
            model_name='interinodisponible',
            name='tipo_bolsa',
            field=models.CharField(choices=[('0', 'Bolsa 0'), ('1', 'Bolsa 1'), ('2', 'Bolsa 2'), ('2D', 'Bolsa 2D'), ('2F', 'Bolsa 2F'), ('2H', 'Bolsa 2H'), ('2J', 'Bolsa 2J'), ('2K', 'Bolsa 2K'), ('2L', 'Bolsa 2L'), ('2M', 'Bolsa 2M'), ('3', 'Bolsa 3'), ('3G', 'Bolsa 3G'), ('4', 'Bolsa 4'), ('6', 'Bolsa 6'), ('8', 'Bolsa 8'), ('P0', 'Bolsa P0'), ('P1', 'Bolsa P1'), ('P1B', 'Bolsa P1B'), ('P2', 'Bolsa P2'), ('P4', 'Bolsa P4'), ('R1', 'Bolsa R1'), ('2N', 'Bolsa 2N'), ('4E', 'Bolsa 4E'), ('4G', 'Bolsa 4G'), ('7P', 'Bolsa 7P'), ('R1H', 'Bolsa R1H'), ('R1F', 'Bolsa R1F'), ('R1D', 'Bolsa R1D'), ('R1G', 'Bolsa R1G'), ('R1I', 'Bolsa R1I')], max_length=10),
        ),
    ]
