# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelado_bd', '0003_auto_20160420_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinciaOpos2016',
            fields=[
                ('codigo_provincia', models.CharField(db_index=True, max_length=15, primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='localidadopos2016',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelado_bd.ProvinciaOpos2016'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc_destino', to='modelado_bd.LocalidadOpos2016'),
        ),
    ]
