# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelado_bd', '0004_auto_20160408_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='interinodisponible',
            name='elige_ab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interinodisponible',
            name='elige_cr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interinodisponible',
            name='elige_cu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interinodisponible',
            name='elige_gu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interinodisponible',
            name='elige_to',
            field=models.BooleanField(default=False),
        ),
    ]
