# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-21 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelado_bd', '0004_auto_20160420_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ruta',
            new_name='RutasOpos2016',
        ),
    ]
