# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelado_bd', '0005_auto_20160409_1558'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interinodisponible',
            table='interinos_disponibles',
        ),
    ]
