# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('etiqueta', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
    ]
