# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etiqueta',
            options={'ordering': ['etiqueta']},
        ),
        migrations.AlterModelTable(
            name='etiqueta',
            table='etiquetas',
        ),
    ]
