# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_auto_20160324_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etiqueta',
            old_name='etiqueta',
            new_name='valor',
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='igual_que',
            field=models.ManyToManyField(to='documentos.Etiqueta'),
        ),
    ]
