# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_auto_20160324_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etiqueta',
            options={},
        ),
    ]
