# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_auto_20160324_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etiqueta',
            options={'ordering': ['valor']},
        ),
        migrations.RemoveField(
            model_name='etiqueta',
            name='igual_que',
        ),
        migrations.AddField(
            model_name='fichero',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
