# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 15:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_auto_20160324_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichero',
            name='fecha_subida',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
